id: IB0995F57
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:29:34.432772
last_modified: 2023-02-10 00:29:34.432897
source_metadata:
  title: 'Nāgārjuna: Mūlamadhyamakakārikā'
  language: bo
bases:
  '2087':
    base_file: 2087.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
